spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:16.2-alpine://ghost_driver?TC_INITSCRIPT=init_postgres.sql
  jpa:
    hibernate:
      ddl-auto: update
